In [36]:
import pandas as pd

In [37]:
import pandas as pd

data_nouns_dir = "../data/Nouns.csv"
data_verbs_dir = "../data/Verbs.csv"

df_nouns = pd.read_csv(data_nouns_dir, usecols=range(16))
df_verbs = pd.read_csv(data_verbs_dir, usecols=range(16))

In [38]:
df_nouns.head(11)

,Paradigm,Class,Lemma,Stem,PersPoss,Dim,Poss,Pej,Pret,Basic,Form1Surface,Form1Split,Form1Source,Form2Surface,Form2Split,Form2Source
0,NAD,NAD_C,naan,naan,1SgPoss,NONE,NONE,NONE,NONE,Loc,ninaaning,n<<naan>>ing,JDN-2010-Nouns,NaN,NaN,NaN
1,NAD,NAD_C,naan,naan,ExclPoss,NONE,NONE,NONE,NONE,Loc,ninaaninaang,n<<naan>>inaang,JDN-2010-Nouns,NaN,NaN,NaN
2,NAD,NAD_C,naan,naan,InclPoss,NONE,NONE,NONE,NONE,Loc,ginaaninaang,g<<naan>>inaang,JDN-2010-Nouns,NaN,NaN,NaN
3,NAD,NAD_C,naan,naan,2SgPoss,NONE,NONE,NONE,NONE,Loc,ginaaning,g<<naan>>ing,JDN-2010-Nouns,NaN,NaN,NaN
4,NAD,NAD_C,naan,naan,2PlPoss,NONE,NONE,NONE,NONE,Loc,ginaaniwaang,g<<naan>>iwaang,JDN-2010-Nouns,NaN,NaN,NaN
5,NAD,NAD_C,naan,naan,3SgProxPoss,NONE,NONE,NONE,NONE,Loc,onaaning,w<<naan>>ing,JDN-2010-Nouns,NaN,NaN,NaN
6,NAD,NAD_C,naan,naan,3PlProxPoss,NONE,NONE,NONE,NONE,Loc,onaaniwaang,w<<naan>>iwaang,JDN-2010-Nouns,NaN,NaN,NaN
7,NAD,NAD_C,naan,naan,3SgObvPoss,NONE,NONE,NONE,NONE,Loc,onaanining,w<<naan>>ining,JDN-2010-Nouns,NaN,NaN,NaN
8,NAD,NAD_C,naan,naan,3PlObvPoss,NONE,NONE,NONE,NONE,Loc,onaanining,w<<naan>>ining,GUESS,NaN,NaN,NaN
9,NAD,NAD_C,naan,naan,1SgPoss,Dim,NONE,NONE,NONE,Loc,ninaanensing,n<<naan>>ensing,JDN-2010-Nouns,NaN,NaN,NaN
10,NAD,NAD_C,naan,naan,ExclPoss,Dim,NONE,NONE,NONE,Loc,ninaanensinaang,n<<naan>>ensinaang,JDN-2010-Nouns,NaN,NaN,NaN

# Ten annotation for lemma 'naan' (index 0-10):

In [39]:
naan_lst = [
    ("ninaaning", ["ni", "naan", "ing"]),
    ("ninaaninaang", ["ni", "naan", "inaan", "g"]),
    ("ginaaninaang", ["gi", "naan", "inaan", "g"]),
    ("ginaaning", ["gi", "naan", "ing"]),
    ("ginaaniwaang", ["gi", "naan", "iwaa", "ng"]),
    ("onaaning", ["o", "naan", "ing"]),
    ("onaaniwaang", ["o", "naan", "iwaa", "ng"]),
    ("onaanining", ["o", "naan", "ining"]),
    ("onaanining", ["o", "naan", "ining"]),
    ("ninaanensing", ["ni", "naan", "ens", "ing"]),
    ("ninaanensinaang", ["ni", "naan", "ens", "inaan", "g"]),
]

# Ten annotations for lemma 'niigi\'igw':

In [40]:
niigiigw_df = df_nouns[df_nouns['Lemma'] == 'niigi\'igw']
niigiigw_df.sample(10)

,Paradigm,Class,Lemma,Stem,PersPoss,Dim,Poss,Pej,Pret,Basic,Form1Surface,Form1Split,Form1Source,Form2Surface,Form2Split,Form2Source
448,NAD,NAD_Cw,niigi'igw,niigi'igw2,3SgObvPoss,Dim,NONE,Pej,NONE,Loc,oniigi'igoonzhishining,w<<niigi'igw2>>oonzhishining,JDN-2010-Nouns,NaN,NaN,NaN
496,NAD,NAD_Cw,niigi'igw,niigi'igw2,2PlPoss,Dim,Poss,Pej,NONE,ObvPl,giniigi'igoonsimishiwaa',g<<niigi'igw2>>oonsimishiwaa',JDN-2010-Nouns,NaN,giniigi'igoonsimishiwaan,g<<niigi'igw2>>oonsimishiwaan
754,NAD,NAD_Cw,niigi'igw,niigi'igw2,InclPoss,NONE,Poss,Pej,NONE,ProxPl,giniigi'igomishinaanig,g<<niigi'igw2>>omishinaanig,JDN-2010-Nouns,NaN,NaN,NaN
691,NAD,NAD_Cw,niigi'igw,niigi'igw2,InclPoss,NONE,NONE,Pej,NONE,ObvSg,giniigi'igoshinaanin,g<<niigi'igw2>>oshinaanin,JDN-2010-Nouns,NaN,NaN,NaN
684,NAD,NAD_Cw,niigi'igw,niigi'igw2,InclPoss,Dim,NONE,NONE,Pret,ObvSg,giniigi'igoonsinaabaniin,g<<niigi'igw2>>oonsinaabaniin,JDN-2010-Nouns,NaN,NaN,NaN
736,NAD,NAD_Cw,niigi'igw,niigi'igw2,ExclPoss,Dim,Poss,Pej,NONE,ProxPl,niniigi'igoonsimishinaanig,n<<niigi'igw2>>oonsimishinaanig,JDN-2010-Nouns,NaN,NaN,NaN
522,NAD,NAD_Cw,niigi'igw,niigi'igw2,3PlObvPoss,NONE,NONE,NONE,Pret,ObvPl,oniigi'igoniban,w<<niigi'igw2>>oniban,GUESS,NaN,oniigi'igoniban,w<<niigi'igw2>>oniban
744,NAD,NAD_Cw,niigi'igw,niigi'igw2,InclPoss,Dim,NONE,NONE,Pret,ProxPl,giniigi'igoonsinaabaniig,g<<niigi'igw2>>oonsinaabaniig,JDN-2010-Nouns,NaN,NaN,NaN
629,NAD,NAD_Cw,niigi'igw,niigi'igw2,3PlObvPoss,NONE,NONE,NONE,NONE,ObvSg,oniigi'igoni,w<<niigi'igw2>>oniw1,GUESS,NaN,NaN,NaN
616,NAD,NAD_Cw,niigi'igw,niigi'igw2,2SgPoss,Dim,Poss,Pej,NONE,ObvSg,giniigi'igoonsimishan,g<<niigi'igw2>>oonsimishan,JDN-2010-Nouns,NaN,NaN,NaN

In [41]:
niigiigw_lst = [
    ("oniigi'igoonsimining", ["o", "niigi'igw2", "oons", "im", "in", "ing"]),
    ("niniigi'igoonsimishag", ["ni", "niigi'igw2", "oons", "im", "ish", "ag"]),
    ("niniigi'igom", ["ni", "niigi'igw2", "om"]),
    ("giniigi'igoonzhishiwaa'", ["gi", "niigi'igw2", "oonzh", "ish", "iwaa"]),
    ("giniigi'igoonzhishing", ["gi", "niigi'igw2", "oonzh", "ish", "ing"]),
    ("oniigi'igoonsini", ["o", "niigi'igw2", "oons", "ini"]),
    ("giniigi'igomibaniin", ["gi", "niigi'igw2", "om", "ibaniin"]),
    ("oniigi'igoonsimiwaa'", ["o", "niigi'igw2", "oons", "im", "iwaa"]),
    ("giniigi'igoonsimiwaag", ["gi", "niigi'igw2", "oons", "im", "iwaa", "g"]),
    ("niniigi'igominaanig", ["ni", "niigi'igw2", "om", "inaan", "ig"])
]

# Ten annotations for lemma 'shkanzhy':

In [42]:
shkanzhy_df = df_nouns[df_nouns['Lemma'] == 'shkanzhy']
shkanzhy_df.sample(10)

,Paradigm,Class,Lemma,Stem,PersPoss,Dim,Poss,Pej,Pret,Basic,Form1Surface,Form1Split,Form1Source,Form2Surface,Form2Split,Form2Source
846,NAD,NAD_Cy,shkanzhy,shkanzhy2,3SgProxPoss,Dim,Poss,NONE,NONE,Loc,oshkanzhiinsiming,w<<shkanzhy2>>iinsiming,JDN-2010-Nouns,NaN,NaN,NaN
1212,NAD,NAD_Cy,shkanzhy,shkanzhy2,1SgPoss,Dim,NONE,Pej,NONE,ProxSg,nishkanzhiinzhish,n<<shkanzhy2>>iinzhish,JDN-2010-Nouns,NaN,NaN,NaN
1154,NAD,NAD_Cy,shkanzhy,shkanzhy2,InclPoss,Dim,NONE,Pej,NONE,ProxPl,gishkanzhiinzhishinaanig,g<<shkanzhy2>>iinzhishinaanig,JDN-2010-Nouns,NaN,NaN,NaN
1156,NAD,NAD_Cy,shkanzhy,shkanzhy2,2PlPoss,Dim,NONE,Pej,NONE,ProxPl,gishkanzhiinzhishiwaag,g<<shkanzhy2>>iinzhishiwaag,JDN-2010-Nouns,NaN,NaN,NaN
967,NAD,NAD_Cy,shkanzhy,shkanzhy2,1SgPoss,Dim,Poss,NONE,Pret,ObvPl,nishkanzhiinsimibanii',n<<shkanzhy2>>iinsimibanii',JDN-2010-Nouns,nishkanzhiinsimibaniin,n<<shkanzhy2>>iinsimibaniin,JDN-2010-Nouns
876,NAD,NAD_Cy,shkanzhy,shkanzhy2,3PlObvPoss,Dim,NONE,Pej,NONE,Loc,oshkanzhiinzhishining,w<<shkanzhy2>>iinzhishining,GUESS,NaN,NaN,NaN
1210,NAD,NAD_Cy,shkanzhy,shkanzhy2,2SgPoss,Dim,Poss,NONE,Pret,ProxSg,gishkanzhiinsimiban,g<<shkanzhy2>>iinsimiban,JDN-2010-Nouns,NaN,NaN,NaN
1005,NAD,NAD_Cy,shkanzhy,shkanzhy2,InclPoss,NONE,Poss,NONE,NONE,ObvSg,gishkanzhiiminaanin,g<<shkanzhy2>>iiminaanin,JDN-2010-Nouns,NaN,NaN,NaN
884,NAD,NAD_Cy,shkanzhy,shkanzhy2,3SgObvPoss,Dim,Poss,Pej,NONE,Loc,oshkanzhiinsimishining,w<<shkanzhy2>>iinsimishining,JDN-2010-Nouns,NaN,NaN,NaN
950,NAD,NAD_Cy,shkanzhy,shkanzhy2,ExclPoss,NONE,Poss,NONE,Pret,ObvPl,nishkanzhiiminaabanii',n<<shkanzhy2>>iiminaabanii',JDN-2010-Nouns,nishkanzhiiminaabaniin,n<<shkanzhy2>>iiminaabaniin,JDN-2010-Nouns

In [43]:
shkanzhy_lst = [
    ("gishkanzhiiminaabanii'", ["gi", "shkanzhy2", "iim", "inaan", "aban", "ii"]),
    ("oshkanzhiiminiban", ["o", "shkanzhy2", "iim", "in", "ban"]),
    ("gishkanzhiinsiminaani'", ["gi", "shkanzhy2", "iins", "im", "inaan", "i"]),
    ("oshkanzhiini", ["o", "shkanzhy2", "iini"]),
    ("gishkanzhiinzhishag", ["gi", "shkanzhy2", "iins", "ish", "ag"]),
    ("oshkanzhiinsiwaang", ["o", "shkanzhy2", "iins", "iwaa", "ng"]),
    ("gishkanzhiimiwaa'", ["gi", "shkanzhy2", "iim", "iwaa"]),
    ("gishkanzhiinsiminaanin", ["gi", "shkanzhy2", "iins", "im", "inaan", "in"]),
    ("gishkanzhiimag", ["gi", "shkanzhy2", "iim", "ag"]),
    ("gishkanzhiimiwaag", ["gi", "shkanzhy2", "iim", "iwaa", "g"])
]

In [44]:
lst = naan_lst + niigiigw_lst + shkanzhy_lst

# Ten annotations for lemma 'dawemaaw':

In [45]:
dawemaaw_df = df_nouns[df_nouns['Lemma'] == 'dawemaaw']
dawemaaw_df.sample(10)

,Paradigm,Class,Lemma,Stem,PersPoss,Dim,Poss,Pej,Pret,Basic,Form1Surface,Form1Split,Form1Source,Form2Surface,Form2Split,Form2Source
1411,NAD,NAD_VV,dawemaaw,dawemaaw2,ExclPoss,NONE,Poss,NONE,NONE,ObvSg,nidawemaaminaanin,n<<dawemaaw2>>minaanin,JDN-2010-Nouns,NaN,NaN,NaN
1511,NAD,NAD_VV,dawemaaw,dawemaaw2,InclPoss,NONE,NONE,NONE,NONE,ProxPl,gidawemaanaanig,g<<dawemaaw2>>naanig,JDN-2010-Nouns,NaN,NaN,NaN
1313,NAD,NAD_VV,dawemaaw,dawemaaw2,InclPoss,Dim,NONE,NONE,NONE,ObvPl,gidawemaansinaani',g<<dawemaaw2>>nsinaani',JDN-2010-Nouns,gidawemaansinaanin,g<<dawemaaw2>>nsinaanin,JDN-2010-Nouns
1496,NAD,NAD_VV,dawemaaw,dawemaaw2,3SgProxPoss,Dim,NONE,Pej,NONE,ObvSg,odawemaanzhishan,w<<dawemaaw2>>nzhishan,JDN-2010-Nouns,NaN,NaN,NaN
1263,NAD,NAD_VV,dawemaaw,dawemaaw2,3PlProxPoss,NONE,NONE,Pej,NONE,Loc,odawemaawishiwaang,w<<dawemaaw2>>ishiwaang,JDN-2010-Nouns,NaN,NaN,NaN
1441,NAD,NAD_VV,dawemaaw,dawemaaw2,2PlPoss,NONE,NONE,Pej,NONE,ObvSg,gidawemaawishiwaan,g<<dawemaaw2>>ishiwaan,JDN-2010-Nouns,NaN,NaN,NaN
1581,NAD,NAD_VV,dawemaaw,dawemaaw2,InclPoss,Dim,NONE,NONE,NONE,ProxSg,gidawemaansinaan,g<<dawemaaw2>>nsinaan,JDN-2010-Nouns,NaN,NaN,NaN
1351,NAD,NAD_VV,dawemaaw,dawemaaw2,2PlPoss,NONE,NONE,NONE,Pret,ObvPl,gidawemaawaabanii',g<<dawemaaw2>>waabanii',JDN-2010-Nouns,gidawemaawaabaniin,g<<dawemaaw2>>waabaniin,JDN-2010-Nouns
1249,NAD,NAD_VV,dawemaaw,dawemaaw2,ExclPoss,Dim,Poss,NONE,NONE,Loc,nidawemaansiminaang,n<<dawemaaw2>>nsiminaang,JDN-2010-Nouns,NaN,NaN,NaN
1419,NAD,NAD_VV,dawemaaw,dawemaaw2,1SgPoss,Dim,NONE,NONE,NONE,ObvSg,nidawemaansan,n<<dawemaaw2>>nsan,JDN-2010-Nouns,NaN,NaN,NaN

In [46]:
dawemaaw_lst = [
    ("gidawemaawisha'", ["gi", "dawemaaw2", "ish", "a"]),
    ("gidawemaansimishan", ["gi", "dawemaaw2", "ns", "im", "ish", "an"]),
    ("nidawemaansinaanig", ["ni", "dawemaaw2", "ns", "inaan", "ig"]),
    ("nidawemaans", ["ni", "dawemaaw2", "ns"]),
    ("nidawemaansimishinaanig", ["ni", "dawemaaw2", "ns", "im", "ish", "inaan", "ig"]),
    ("nidawemaansimag", ["ni", "dawemaaw2", "ns", "im", "ag"]),
    ("gidawemaamishinaanin", ["gi", "dawemaaw2", "m", "ish", "inaan", "in"]),
    ("odawemaawaabaniin", ["o", "dawemaaw2", "waa", "aban", "iin"]),
    ("gidawemaansiminaaban", ["gi", "dawemaaw2", "ns", "im", "inaan", "aban"]),
    ("nidawemaan", ["ni", "dawemaaw2", "n"])
]

# Ten annotation for lemma 'daangosheny':

In [47]:
daangosheny_df = df_nouns[df_nouns['Lemma'] == 'daangosheny']
daangosheny_df.sample(10)

,Paradigm,Class,Lemma,Stem,PersPoss,Dim,Poss,Pej,Pret,Basic,Form1Surface,Form1Split,Form1Source,Form2Surface,Form2Split,Form2Source
1630,NAD,NAD_VVny,daangosheny,daangosheny1,InclPoss,NONE,NONE,NONE,NONE,Loc,gidaangoshenyinaang,g<<daangosheny1>>inaang,JDN-2010-Nouns,NaN,NaN,NaN
1988,NAD,NAD_VVny,daangosheny,daangosheny1,InclPoss,Dim,NONE,NONE,NONE,ProxSg,gidaangoshenyensinaan,g<<daangosheny1>>ensinaan,JDN-2010-Nouns,NaN,NaN,NaN
1937,NAD,NAD_VVny,daangosheny,daangosheny1,ExclPoss,NONE,NONE,Pej,NONE,ProxPl,nindaangoshenyishinaanig,n<<daangosheny1>>ishinaanig,JDN-2010-Nouns,NaN,NaN,NaN
1784,NAD,NAD_VVny,daangosheny,daangosheny1,2SgPoss,Dim,Poss,NONE,Pret,ObvPl,gidaangoshenyensimibanii',g<<daangosheny1>>ensimibanii',JDN-2010-Nouns,gidaangoshenyensimibaniin,g<<daangosheny1>>ensimibaniin,JDN-2010-Nouns
1924,NAD,NAD_VVny,daangosheny,daangosheny1,2SgPoss,NONE,Poss,NONE,NONE,ProxPl,gidaangoshenyimag,g<<daangosheny1>>imag,JDN-2010-Nouns,NaN,NaN,NaN
1891,NAD,NAD_VVny,daangosheny,daangosheny1,InclPoss,Dim,Poss,NONE,Pret,ObvSg,gidaangoshenyensiminaabaniin,g<<daangosheny1>>ensiminaabaniin,JDN-2010-Nouns,NaN,NaN,NaN
1762,NAD,NAD_VVny,daangosheny,daangosheny1,3PlObvPoss,NONE,NONE,NONE,Pret,ObvPl,odaangoshenyiniban,w<<daangosheny1>>iniban,GUESS,odaangoshenyiniban,w<<daangosheny1>>iniban,GUESS
1655,NAD,NAD_VVny,daangosheny,daangosheny1,1SgPoss,Dim,Poss,NONE,NONE,Loc,nindaangoshenyensiming,n<<daangosheny1>>ensiming,JDN-2010-Nouns,NaN,NaN,NaN
1792,NAD,NAD_VVny,daangosheny,daangosheny1,InclPoss,Dim,NONE,Pej,NONE,ObvPl,gidaangoshenyenzhishinaani',g<<daangosheny1>>enzhishinaani',JDN-2010-Nouns,gidaangoshenyenzhishinaanin,g<<daangosheny1>>enzhishinaanin,JDN-2010-Nouns
1676,NAD,NAD_VVny,daangosheny,daangosheny1,2SgPoss,NONE,Poss,Pej,NONE,Loc,gidaangoshenyimishing,g<<daangosheny1>>imishing,JDN-2010-Nouns,NaN,NaN,NaN

In [48]:
daangosheny_lst = [
    ("odaangoshenyimishini", ["o", "daangosheny1", "im", "ish", "ini"]),
    ("odaangoshenyimishini", ["o", "daangosheny1", "im", "ish", "ini"]),
    ("odaangoshenyensimisha'", ["o", "daangosheny1", "ens", "im", "ish", "a"]),
    ("nindaangoshenyensibaniig", ["ni", "daangosheny1", "ens", "ibaniig"]),
    ("gidaangoshenyishiwaag", ["gi", "daangosheny1", "ish", "iwaa", "g"]),
    ("nindaangoshenyensiman", ["ni", "daangosheny1", "ens", "im", "an"]),
    ("odaangoshenyiman", ["o", "daangosheny1", "im", "an"]),
    ("odaangoshenyimibanii'", ["o", "daangosheny1", "im", "ban", "ii"]),
    ("odaangoshenyensan", ["o", "daangosheny1", "ens", "an"]),
    ("odaangoshenyensing", ["o", "daangosheny1", "ens", "ing"])
]

In [49]:
lst = naan_lst + niigiigw_lst + shkanzhy_lst + dawemaaw_lst + daangosheny_lst

In [50]:
lst

[('ninaaning', ['ni', 'naan', 'ing']),
 ('ninaaninaang', ['ni', 'naan', 'inaan', 'g']),
 ('ginaaninaang', ['gi', 'naan', 'inaan', 'g']),
 ('ginaaning', ['gi', 'naan', 'ing']),
 ('ginaaniwaang', ['gi', 'naan', 'iwaa', 'ng']),
 ('onaaning', ['o', 'naan', 'ing']),
 ('onaaniwaang', ['o', 'naan', 'iwaa', 'ng']),
 ('onaanining', ['o', 'naan', 'ining']),
 ('onaanining', ['o', 'naan', 'ining']),
 ('ninaanensing', ['ni', 'naan', 'ens', 'ing']),
 ('ninaanensinaang', ['ni', 'naan', 'ens', 'inaan', 'g']),
 ("oniigi'igoonsimining", ['o', "niigi'igw2", 'oons', 'im', 'in', 'ing']),
 ("niniigi'igoonsimishag", ['ni', "niigi'igw2", 'oons', 'im', 'ish', 'ag']),
 ("niniigi'igom", ['ni', "niigi'igw2", 'om']),
 ("giniigi'igoonzhishiwaa'", ['gi', "niigi'igw2", 'oonzh', 'ish', 'iwaa']),
 ("giniigi'igoonzhishing", ['gi', "niigi'igw2", 'oonzh', 'ish', 'ing']),
 ("oniigi'igoonsini", ['o', "niigi'igw2", 'oons', 'ini']),
 ("giniigi'igomibaniin", ['gi', "niigi'igw2", 'om', 'ibaniin']),
 ("oniigi'igoonsimiwaa'", ['o', "niigi'igw2", 'oons', 'im', 'iwaa']),
 ("giniigi'igoonsimiwaag", ['gi', "niigi'igw2", 'oons', 'im', 'iwaa', 'g']),
 ("niniigi'igominaanig", ['ni', "niigi'igw2", 'om', 'inaan', 'ig']),
 ("gishkanzhiiminaabanii'", ['gi', 'shkanzhy2', 'iim', 'inaan', 'aban', 'ii']),
 ('oshkanzhiiminiban', ['o', 'shkanzhy2', 'iim', 'in', 'ban']),
 ("gishkanzhiinsiminaani'", ['gi', 'shkanzhy2', 'iins', 'im', 'inaan', 'i']),
 ('oshkanzhiini', ['o', 'shkanzhy2', 'iini']),
 ('gishkanzhiinzhishag', ['gi', 'shkanzhy2', 'iins', 'ish', 'ag']),
 ('oshkanzhiinsiwaang', ['o', 'shkanzhy2', 'iins', 'iwaa', 'ng']),
 ("gishkanzhiimiwaa'", ['gi', 'shkanzhy2', 'iim', 'iwaa']),
 ('gishkanzhiinsiminaanin', ['gi', 'shkanzhy2', 'iins', 'im', 'inaan', 'in']),
 ('gishkanzhiimag', ['gi', 'shkanzhy2', 'iim', 'ag']),
 ('gishkanzhiimiwaag', ['gi', 'shkanzhy2', 'iim', 'iwaa', 'g']),
 ("gidawemaawisha'", ['gi', 'dawemaaw2', 'ish', 'a']),
 ('gidawemaansimishan', ['gi', 'dawemaaw2', 'ns', 'im', 'ish', 'an']),
 ('nidawemaansinaanig', ['ni', 'dawemaaw2', 'ns', 'inaan', 'ig']),
 ('nidawemaans', ['ni', 'dawemaaw2', 'ns']),
 ('nidawemaansimishinaanig',
  ['ni', 'dawemaaw2', 'ns', 'im', 'ish', 'inaan', 'ig']),
 ('nidawemaansimag', ['ni', 'dawemaaw2', 'ns', 'im', 'ag']),
 ('gidawemaamishinaanin', ['gi', 'dawemaaw2', 'm', 'ish', 'inaan', 'in']),
 ('odawemaawaabaniin', ['o', 'dawemaaw2', 'waa', 'aban', 'iin']),
 ('gidawemaansiminaaban', ['gi', 'dawemaaw2', 'ns', 'im', 'inaan', 'aban']),
 ('nidawemaan', ['ni', 'dawemaaw2', 'n']),
 ('odaangoshenyimishini', ['o', 'daangosheny1', 'im', 'ish', 'ini']),
 ('odaangoshenyimishini', ['o', 'daangosheny1', 'im', 'ish', 'ini']),
 ("odaangoshenyensimisha'", ['o', 'daangosheny1', 'ens', 'im', 'ish', 'a']),
 ('nindaangoshenyensibaniig', ['ni', 'daangosheny1', 'ens', 'ibaniig']),
 ('gidaangoshenyishiwaag', ['gi', 'daangosheny1', 'ish', 'iwaa', 'g']),
 ('nindaangoshenyensiman', ['ni', 'daangosheny1', 'ens', 'im', 'an']),
 ('odaangoshenyiman', ['o', 'daangosheny1', 'im', 'an']),
 ("odaangoshenyimibanii'", ['o', 'daangosheny1', 'im', 'ban', 'ii']),
 ('odaangoshenyensan', ['o', 'daangosheny1', 'ens', 'an']),
 ('odaangoshenyensing', ['o', 'daangosheny1', 'ens', 'ing'])]